workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "FIRST_PROJECT.xcworkspace"
        XCODE_SCHEME: "YOUR_SCHEME"
    scripts:
      - name: Cocoapods installation
          script: |
            cd $CM_BUILD_DIR/iosApp
            pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          cd $CM_BUILD_DIR/iosApp
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
      artifacts:
        - iosApp/build/ios/ipa/*.ipa