workflows:
  ios-workflow:
    name: KMM iOS Workflow
    instance_type: mac_mini_m2

    max_build_duration: 120

    environment:
      vars:
        XCODE_PROJECT: "iosApp.xcodeproj"
        XCODE_SCHEME: "iosApp"

      xcode: latest
      java: 21

    triggering:
      events:
        - push
        - pull_request

    scripts:
      - name: Set up Gradle Wrapper permissions
        script: |
          chmod +x ./gradlew

      - name: Build Kotlin Multiplatform iOS Framework
        script: |
          ./gradlew :composeApp:linkReleaseFrameworkIosArm64

      - name: Build IPA for distribution
        script: |
          cd $CM_BUILD_DIR/iosApp
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --clean

    artifacts:
      - iosApp/build/ipa/*.ipa